# 基本状态

- Promise 存在三个状态 pending, fulfilled, rejected
- pending 为初始状态，并可以转化为 `fulfilled`, `rejected`
- fulfilled, 不可转为其他状态，且必须又一个不可改变的值
- rejected, 不可转为其他状态，且必须又一个不可改变的原因
- `new Promise((resolve, reject)=>{resolve(value)})` resolve 为成功，接收参数 value，状态改变为 fulfilled，不可再次改变。
- `new Promise((resolve, reject)=>{reject(reason)})` reject 为失败，接收参数 reason，状态改变为 rejected，不可再次改变。
- 若是 executor 函数报错 直接执行 reject();

# then 方法

参数 `onFulfilled`, `onRejected`, 成功有成功值，失败有失败的原因。

# 异步问题

现在基本可以实现简单的同步代码，但是当 resolve 在 setTomeout 内执行，then 时 state 还是 pending 等待状态 我们就需要在 then 调用的时候，将成功和失败存到各自的数组，一旦 reject 或者 resolve，就调用它们, 用在多次调用 p1.then(res1,rej1), p1.then(res2,rej2)

# 解决链式调用

我门常常用到 new Promise().then().then(),这就是链式调用，用来解决回调地狱

- 为了达成链式，我们默认在第一个 then 里返回一个 promise。秘籍规定了一种方法，就是在 then 里面返回一个新的 promise,称为 promise2：promise2 = new Promise((resolve, reject)=>{})
  - 将这个 promise2 返回的值传递到下一个 then 中
  - 如果返回一个普通的值，则将普通的值传递给下一个 then 中
- 当我们在第一个 then 中 return 了一个参数（参数未知，需判断）。这个 return 出来的新的 promise 就是 onFulfilled()或 onRejected()的值
  - 首先，要看 x 是不是 promise。
  - 如果是 promise，则取它的结果，作为新的 promise2 成功的结果
  - 如果是普通值，直接作为 promise2 成功的结果
  - 所以要比较 x 和 promise2
  - resolvePromise 的参数有 promise2（默认返回的 promise）、x（我们自己 return 的对象）、resolve、reject
  - resolve 和 reject 是 promise2 的

# 完成 resolvePromise 函数

# 解决其他问题

## code

```JavaScript
class Promise{
  constructor(executor){
    this.state = 'pending'; // 状态
    this.value = undefined; // 成功的值
    this.reason = undefined; // 失败的理由
    this.onResolvedCallbacks = []; // 储存异步成功状态 用在多次调用 p1.then(res1,rej1), p1.then(res2,rej2)
    this.onRejectedCallbacks = []; // 储存异步失败状态
    let resolve = value => {
      if (this.state === 'pending') {
        this.state = 'fulfilled';
        this.value = value;
        this.onResolvedCallbacks.forEach(fn=>fn());
      }
    };
    let reject = reason => {
      if (this.state === 'pending') {
        this.state = 'rejected';
        this.reason = reason;
        this.onRejectedCallbacks.forEach(fn=>fn());
      }
    };
    try{
      executor(resolve, reject);
    } catch (err) {
      reject(err);
    }
  }
  then(onFulfilled,onRejected) {
    onFulfilled = typeof onFulfilled === 'function' ? onFulfilled : value => value;
    onRejected = typeof onRejected === 'function' ? onRejected : err => { throw err };
    let promise2 = new Promise((resolve, reject) => {
      if (this.state === 'fulfilled') {
        setTimeout(() => { // onFulfilled或onRejected不能同步被调用，必须异步调用。我们就用setTimeout解决异步问题
          try {
            let x = onFulfilled(this.value);
            resolvePromise(promise2, x, resolve, reject);
          } catch (e) {
            reject(e);
          }
        }, 0);
      };
      if (this.state === 'rejected') {
        setTimeout(() => {
          try {
            let x = onRejected(this.reason);
            resolvePromise(promise2, x, resolve, reject);
          } catch (e) {
            reject(e);
          }
        }, 0);
      };
      if (this.state === 'pending') {
        this.onResolvedCallbacks.push(() => {
          setTimeout(() => {
            try {
              let x = onFulfilled(this.value);
              resolvePromise(promise2, x, resolve, reject);
            } catch (e) {
              reject(e);
            }
          }, 0);
        });
        this.onRejectedCallbacks.push(() => {
          setTimeout(() => {
            try {
              let x = onRejected(this.reason);
              resolvePromise(promise2, x, resolve, reject);
            } catch (e) {
              reject(e);
            }
          }, 0)
        });
      };
    });
    return promise2;
  }
  catch(fn){
    return this.then(null,fn);
  }
}
function resolvePromise(promise2, x, resolve, reject){
  if(x === promise2){
    return reject(new TypeError('Chaining cycle detected for promise'));
  }
  let called;
  if (x != null && (typeof x === 'object' || typeof x === 'function')) {
    try {
      let then = x.then;
      if (typeof then === 'function') {
        then.call(x, y => {
          if(called)return;
          called = true;
          resolvePromise(promise2, y, resolve, reject);
        }, err => {
          if(called)return;
          called = true;
          reject(err);
        })
      } else {
        resolve(x);
      }
    } catch (e) {
      if(called)return;
      called = true;
      reject(e);
    }
  } else {
    resolve(x);
  }
}
//resolve方法
Promise.resolve = function(val){
  return new Promise((resolve,reject)=>{
    resolve(val)
  });
}
//reject方法
Promise.reject = function(val){
  return new Promise((resolve,reject)=>{
    reject(val)
  });
}
//race方法
Promise.race = function(promises){
  return new Promise((resolve,reject)=>{
    for(let i=0;i<promises.length;i++){
      promises[i].then(resolve,reject)
    };
  })
}
//all方法(获取所有的promise，都执行then，把结果放到数组，一起返回)
Promise.all = function(promises){
  let arr = [];
  let i = 0;
  function processData(index,data){
    arr[index] = data;
    i++;
    if(i == promises.length){
      resolve(arr);
    };
  };
  return new Promise((resolve,reject)=>{
    for(let i=0;i<promises.length;i++){
      promises[i].then(data=>{
        processData(i,data);
      },reject);
    };
  });
}
```

## async await

```JavaScript
async function async1() {
    console.log('async1 start');
    await async2();
    console.log('async1 end');
}

// 相当于
async function async1() {
    console.log('async1 start');
    Promise.resolve(async2()).then(() => {
      console.log('async1 end');
  })
}
```
